workflows:
  flutter-ios-simulator:
    name: Flutter iOS Simulator Build
    max_build_duration: 120 # В минутах
    instance_type: mac_mini_m2 # Или mac_mini_m1 для экономии

    environment:
      flutter: stable # Версия Flutter (stable, beta или dev)
      xcode: latest # Последняя версия Xcode
      cocoapods: default # Автоматически запустит pod install, если нужно

    scripts:
      - name: Установить зависимости Flutter
        script: flutter pub get

      - name: Установить Pods (если нужно)
        script: |
          if [ -f ios/Podfile ]; then
            cd ios && pod install
            cd ..
          fi

      - name: Собрать для симулятора (без подписи)
        script: flutter build ios --debug --no-codesign --simulator

      - name: Запаковать артефакт
        script: |
          APP_DIR="build/ios/iphonesimulator/Runner.app"
          ZIP_FILE="Runner-simulator.zip"
          if [ -d "$APP_DIR" ]; then
            zip -r "$ZIP_FILE" "$APP_DIR"
          else
            echo "App directory not found!"
            exit 1
          fi

    artifacts:
      - build/ios/iphonesimulator/**/*.app # Точный путь для симулятора
      - Runner-simulator.zip # ZIP, если скрипт сработал
