workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable # Or the specific Flutter version you need
      xcode: latest # Or the specific Xcode version you need
    scripts:
      - name: Build for iOS Simulator
        script: |
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.2' \ # Adjust simulator name and OS version as needed
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
